dist: xenial

language: java

jdk:
  - openjdk8
  - openjdk11

services:
  - docker

before_install:
  - echo > maven-publish.gradle
  - docker run -d -p 2379:2379 gcr.io/etcd-development/etcd
  - netstat -a -n
