dist: xenial

language: java

jdk:
  - openjdk8
  - openjdk11

services:
  - docker

before_install:
  - echo > maven-publish.gradle
  - docker run -d -p 127.0.0.1:2379:2379 gcr.io/etcd-development/etcd etcd --listen-client-urls 'http://0.0.0.0:2379' --advertise-client-urls 'http://localhost:2379'
  - curl -L http://127.0.0.1:2379/version
