dist: xenial

language: java

jdk:
  - openjdk8
  - openjdk11

services:
  - docker

before_install:
  - echo > maven-publish.gradle

script:
  - docker run -d -p 127.0.0.1:2379:2379 gcr.io/etcd-development/etcd
  - gradle check -i
